import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

// Statically embed translation data to prevent module resolution errors.
const enTranslations: Record<string, string> = {
    "appTitle": "Alfanumrik",
    "appSubtitle": "Unlock Your Brilliance",
    "home": "Home",
    "welcomeLearner": "Welcome, Learner!",
    "selectGradePrompt": "Please select your grade to begin your learning journey.",
    "backToGrades": "Back to Grades",
    "chooseSubject": "Choose a Subject",
    "subjects": "Subjects",
    "chaptersIn": "Chapters in",
    "notSureStart": "Not sure where to start?",
    "takeDiagnosticTest": "Take a Diagnostic Test",
    "selectSubjectPrompt": "Select a subject to see its chapters.",
    "preparingLesson": "Preparing your lesson...",
    "oopsError": "Oops! Something went wrong.",
    "tryAgain": "Try Again",
    "quizComplete": "Quiz Complete!",
    "youScored": "You scored {{score}} out of {{total}}",
    "aiAnalyzing": "AI is analyzing your results...",
    "yourNextStep": "Your Next Step",
    "backToChapters": "Back to Chapters",
    "continueToNextChapter": "Continue to Next Chapter",
    "reviewThisChapter": "Review This Chapter",
    "goTo": "Go to",
    "loadedFromDB": "Loaded from DB",
    "chapterMastery": "Chapter Mastery",
    "keyConcepts": "Key Concepts",
    "chapterSummary": "Chapter Summary",
    "readyToTest": "Ready to test your knowledge?",
    "takeQuizPrompt": "Take the quiz to update your progress and master new concepts.",
    "generateAdaptiveQuiz": "Generate Adaptive Quiz",
    "aiCreatingQuiz": "AI is creating your quiz...",
    "chapterMasteredCongrats": "Congratulations! You've mastered this chapter.",
    "mastered": "Mastered",
    "inProgress": "In Progress",
    "notStarted": "Not Started",
    "markAsUnderstood": "I've read this, mark as understood",
    "stemConnection": "STEM Connection & Real-World Example",
    "visualDiagram": "Visual Diagram",
    "aiDrawingDiagram": "AI is drawing your diagram...",
    "diagramFailedError": "AI failed to create a diagram.",
    "unknownError": "An unknown error occurred.",
    "quizGenerationError": "Failed to generate quiz.",
    "recommendationError": "Could not generate recommendation.",
    "quizResults": "Quiz Results",
    "chapter": "Chapter",
    "quizScoreSummary": "You answered {{score}} out of {{total}} questions correctly.",
    "reviewAnswers": "Review Your Answers",
    "concept": "Concept",
    "yourAnswer": "Your answer",
    "notAnswered": "Not answered",
    "correctAnswerLabel": "Correct answer",
    "explanation": "Explanation",
    "backToLesson": "Back to Lesson",
    "adaptiveQuiz": "Adaptive Quiz",
    "question": "Question",
    "testingConcept": "Testing Concept",
    "previous": "Previous",
    "next": "Next",
    "finishQuiz": "Finish Quiz",
    "preparingDiagnosticTest": "AI is preparing your diagnostic test...",
    "testGenerationError": "Failed to generate test.",
    "couldNotCreateTest": "Could not create test.",
    "backToSubjects": "Back to Subjects",
    "testComplete": "Test Complete!",
    "ourRecommendation": "Our Recommendation",
    "diagnosticTestFor": "Diagnostic Test",
    "diagnosticResultHigh": "You have a strong foundation in {{subject}}! You can confidently start with any chapter, or perhaps challenge yourself with \"{{chapter}}\".",
    "diagnosticResultMid": "You're off to a good start! We recommend beginning with the first chapter, \"{{chapter}},\" to solidify your understanding.",
    "diagnosticResultLow": "No worries, every expert starts somewhere! Let's build a strong foundation together. The best place to start is the first chapter: \"{{chapter}}\".",
    "welcomeToPlatform": "Welcome to Alfanumrik!",
    "selectRolePrompt": "Please select your role to continue.",
    "roleStudent": "Student",
    "roleStudentDesc": "Start your personalized learning journey.",
    "roleTeacher": "Teacher",
    "roleTeacherDesc": "Monitor progress and generate reports.",
    "roleParent": "Parent",
    "roleParentDesc": "View your child's progress and reports.",
    "backToRoleSelection": "Back to Role Selection",
    "teacherDashboard": "Teacher Dashboard",
    "teacherDashboardPrompt": "Select a student to view their academic performance and generate reports.",
    "parentDashboard": "Parent Dashboard",
    "parentDashboardPrompt": "Here's an overview of your child's progress. Select their profile to view a detailed report.",
    "backToDashboard": "Back to Dashboard",
    "aiTools": "AI Tools",
    "generatingReport": "Generating Report...",
    "generateAnalysisReport": "Generate Analysis Report",
    "assigningSheet": "Assigning Sheet...",
    "assignPracticeSheet": "Assign Practice Sheet",
    "aiGeneratedReport": "AI Generated Report",
    "practiceSheet": "Practice Sheet",
    "askFitto": "Ask Fitto",
    "yourQuestion": "Your question",
    "askQuestionPlaceholder": "Type your question here for Fitto...",
    "cancel": "Cancel",
    "submitQuestion": "Submit Question",
    "fittoIsThinking": "Fitto is thinking...",
    "fittoResponseTitle": "Fitto's Answer",
    "fittoWelcome": "Hello! Do you have any questions about '{{concept}}'? I'm here to help!",
    "performance": "Performance",
    "studentQuestions": "Student Questions",
    "aiReports": "AI Reports",
    "noPerformanceData": "No performance data available yet.",
    "noPerformanceDataError": "No performance data available to identify a weak area.",
    "context": "Context",
    "modelAnswer": "Model Answer",
    "pedagogicalNotes": "Pedagogical Notes (for teacher)",
    "getAIAnswerSuggestion": "Get AI Teacher Notes",
    "analyzing": "Analyzing",
    "noQuestionsSubmitted": "This student hasn't submitted any questions yet.",
    "errorFetchingQuestions": "Error fetching student questions.",
    "welcomeBack": "Welcome back, {{name}}!",
    "dashboardSubtitle": "Let's make today a great day for learning.",
    "whatsNext": "What's next?",
    "continueLearningPrompt": "Pick up where you left off or explore a new subject.",
    "startLearning": "Start Learning",
    "fittoRecommendations": "Fitto's Recommendations",
    "practiceThisConcept": "Practice this Concept",
    "generateExercises": "Generate Exercises",
    "generatingExercises": "Generating Exercises...",
    "exerciseSummary": "Exercise Summary",
    "yourScore": "Your Score",
    "correct": "Correct!",
    "incorrect": "Incorrect",
    "close": "Close",
    "quizType": "Quiz",
    "exerciseType": "Practice Exercise",
    "practiceOn": "Practice: {{context}}",
    "nextQuestion": "Next Question",
    "finishPractice": "Finish Practice",
    "seeExplanation": "See Explanation",
    "studentLoginTitle": "Student Login",
    "studentLoginSubtitle": "Enter your details to start learning.",
    "studentNameLabel": "Student Name",
    "studentNamePlaceholder": "e.g., Ananya Sharma",
    "gradeLabel": "Grade",
    "selectGradePlaceholder": "Select your Grade",
    "loginButton": "Login",
    "logoutButton": "Logout",
    "loginError": "Login failed. Please check your name and grade.",
    "backToRoles": "Back to Roles",
    "studyPatternsAndTrends": "Study Patterns & Trends",
    "todaysMission": "Today's Mission",
    "missionPrompt": "The AI has crafted a personalized next step for you.",
    "beginMission": "Begin Today's Mission",
    "browseCurriculum": "Browse Full Curriculum",
    "craftingYourPath": "Crafting your personalized path...",
    "aiReasoning": "Here's why:",
    "missionComplete": "Mission Complete!",
    "greatWork": "Great work! You've completed your personalized task for today.",
    "todaysTask": "Today's Task",
    "iqChallenge": "IQ Challenge",
    "eqChallenge": "Emotional Intelligence Scenario",
    "bestResponse": "Best Response",
    "skill": "Skill",
    "recentActivity": "Recent Activity",
    "academicChapter": "{{chapter}} in {{subject}}",
    "iqChallengeCompleted": "IQ Challenge Completed",
    "eqChallengeCompleted": "EQ Challenge Completed",
    "badgeMastery": "Mastery",
    "badgeProficient": "Proficient",
    "badgeImproving": "Improving",
    "rec_welcome": "Welcome! Complete your first activity to get personalized recommendations from Fitto.",
    "rec_strength": "Wow, fantastic work on '{{context}}' ({{score}}%)! You have a real talent for {{subject}}. Why not challenge yourself with the next chapter?",
    "rec_weakness": "It looks like '{{context}}' in {{subject}} was a bit tricky ({{score}}%). That's okay! Try the practice exercises to build confidence.",
    "rec_general_tip": "A curious mind learns best! Don't forget to use the 'Ask Fitto' feature if you have any questions.",
    "studyPatterns": "Study Patterns",
    "weeklyActivity": "Weekly Activity",
    "lessActivity": "Less",
    "moreActivity": "More",
    "performanceBySubject": "Performance by Subject",
    "learningStyle": "Learning Style Analysis",
    "quizzesTaken": "Quizzes Taken",
    "practiceSessions": "Practice Sessions",
    "errorCraftingPathTitle": "Couldn't Craft Your Path",
    "errorCraftingPathBody": "There was an issue while communicating with our AI. Please try again.",
    "retryButton": "Retry",
    "formulaSheet": "Formula Sheet",
    "problemSolvingGuides": "Problem-Solving Guides",
    "practiceProblems": "Practice Problems",
    "conceptual": "Conceptual",
    "application": "Application",
    "higherOrderThinking": "Higher-Order Thinking",
    "viewSolution": "View Solution",
    "commonMistakes": "Common Mistakes",
    "competitiveExamCorner": "Competitive Exam Corner",
    "experimentsAndSafety": "Experiments & Safety",
    "materialsNeeded": "Materials Needed",
    "safetyFirst": "Safety First!",
    "scientificMethodInAction": "Scientific Method in Action",
    "latestDiscoveries": "Latest Discoveries & Technology",
    "environmentalConnection": "Environmental Connection",
    "interdisciplinaryLinks": "Interdisciplinary Links",
    "vocabularyDeepDive": "Vocabulary Deep Dive",
    "etymology": "Etymology",
    "timelineOfEvents": "Timeline of Key Events",
    "keyFigures": "Key Figures & Personalities",
    "primarySourceAnalysis": "Primary Source Analysis",
    "analysis": "Analysis",
    "inDepthCaseStudies": "In-depth Case Studies",
    "background": "Background",
    "conclusion": "Conclusion",
    "grammarSpotlight": "Grammar Spotlight",
    "literaryDeviceAnalysis": "Literary Device Analysis",
    "example": "Example",
    "questionBank": "Question Bank",
    "accessQuestionBank": "Access Question Bank",
    "questionBankTitle": "AI Question Bank Generator",
    "questionBankPrompt": "Select a grade, subject, and chapter to generate a diverse set of questions.",
    "selectChapterPlaceholder": "Select a Chapter",
    "generateQuestions": "Generate Questions",
    "generatingQuestions": "AI is generating questions...",
    "noQuestionsGenerated": "No questions were generated. Please try again.",
    "questionType": "Question Type",
    "mcq": "MCQ",
    "shortAnswer": "Short Answer",
    "longAnswer": "Long Answer",
    "difficulty": "Difficulty",
    "easy": "Easy",
    "medium": "Medium",
    "hard": "Hard",
    "bloomsTaxonomy": "Bloom's Taxonomy",
    "remembering": "Remembering",
    "understanding": "Understanding",
    "applying": "Applying",
    "analyzing": "Analyzing",
    "evaluating": "Evaluating",
    "creating": "Creating",
    "markingScheme": "Marking Scheme",
    "tags": "Tags",
    "competencyBased": "Competency-Based",
    "previousYearQuestion": "Previous Year Question",
    "curriculumGenerator": "Curriculum Generator",
    "curriculumGeneratorPrompt": "Use AI to generate a curriculum outline for a specific grade and subject.",
    "generateOutline": "Generate Outline",
    "generatingOutline": "AI is generating outline...",
    "noOutlineGenerated": "No outline was generated. Please adjust your selections and try again.",
    "downloadAsSql": "Download as SQL",
    "validateCurriculum": "Validate Curriculum",
    "validatingCurriculum": "AI is validating the outline...",
    "qualityReportTitle": "AI Quality Report",
    "validationError": "Failed to get validation report from AI.",
    "listenToChapter": "Listen to Chapter",
    "pauseNarration": "Pause",
    "resumeNarration": "Resume",
    "stopNarration": "Stop narration",
    "ttsNotSupported": "Text-to-Speech is not supported in your browser.",
    "viewPrivacyPolicy": "View Privacy Policy",
    "privacyPolicyTitle": "Our Privacy Policy (for Students!)",
    "backToHome": "Back to Home",
    "privacyIntro": "Hey there! Your privacy is super important to us at Alfanumrik. This page explains in simple terms what information we collect and how we use it to help you learn. Think of it as our promise to keep your learning journey safe and fun!",
    "whatInfoWeCollectTitle": "What Info Do We Collect?",
    "whatInfoWeCollectContent": "When you use our app, we keep track of a few things to make your experience better: Your name and grade, which lessons you study, how you do on quizzes and practice exercises, and any questions you ask our AI mentor, Fitto. We do NOT collect personal information you don't give us, like your address or phone number.",
    "howWeUseInfoTitle": "How Do We Use Your Info?",
    "howWeUseInfoContent": "We use your learning data to create a personalized path just for you! It helps us understand which topics you're great at and where you might need a little more help. This lets our AI suggest the perfect next lesson or exercise for you. For teachers and parents, this information helps them see how you're doing and support you better.",
    "infoSafetyTitle": "How We Keep Your Info Safe",
    "infoSafetyContent": "Your information is protected with strong security, like a secret code that only our system can understand. We only share your progress with your registered teacher and parent. We never sell your information to anyone.",
    "yourChoicesTitle": "Your Choices",
    "yourChoicesContent": "You are in control of your learning journey. You can always ask a parent or teacher to help you see or update your information if something is not right.",
    "changesToPolicyTitle": "Changes to This Policy",
    "changesToPolicyContent": "Sometimes we might update this policy to make it even better. If we make any big changes, we’ll be sure to let your parents or teachers know.",
    "contactUsTitle": "Questions? Ask an Adult to Help!",
    "contactUsContent": "If you have any questions about our privacy promise, please ask a parent or teacher to help you contact us. Happy learning!",
    "academicQuestion": "Academic Question",
    "missionType_ACADEMIC_REVIEW": "Academic Review",
    "missionType_ACADEMIC_PRACTICE": "Academic Practice",
    "missionType_ACADEMIC_NEW": "New Topic Challenge",
    "missionType_IQ_EXERCISE": "Cognitive Skills",
    "missionType_EQ_EXERCISE": "Emotional Intelligence",
    "feedbackOnReport": "Feedback on this report?",
    "helpUsImprove": "Help us improve our AI. Was this report helpful?",
    "submitFeedback": "Submit Feedback",
    "feedbackThanks": "Thank you for your feedback!",
    "commentOptional": "Comment (optional)",
    "noProblemsAvailable": "No problems available for this category.",
    "learningObjectives": "Learning Objectives",
    "keyTheoremsAndProofs": "Key Theorems and Proofs",
    "formulaDerivations": "Formula Derivations",
    "solvedNumericalProblems": "Solved Numerical Problems",
    "keyLawsAndPrinciples": "Key Laws and Principles",
    "conceptMap": "Chapter Concept Map",
    "learningTricksAndMnemonics": "Learning Tricks & Mnemonics",
    // FIX: Add missing comma to prevent syntax error
    "higherOrderThinkingQuestions": "Higher-Order Thinking Corner",
};

const hiTranslations: Record<string, string> = {
    "appTitle": "अल्फान्यूमरिक",
    "appSubtitle": "अपनी प्रतिभा को उजागर करें",
    "home": "होम",
    "welcomeLearner": " आपका स्वागत है, शिक्षार्थी!",
    "selectGradePrompt": "कृपया अपनी सीखने की यात्रा शुरू करने के लिए अपनी कक्षा का चयन करें।",
    "backToGrades": "कक्षाओं पर वापस जाएं",
    "chooseSubject": "एक विषय चुनें",
    "subjects": "विषय",
    "chaptersIn": "अध्याय",
    "notSureStart": "निश्चित नहीं हैं कि कहाँ से शुरू करें?",
    "takeDiagnosticTest": "एक नैदानिक ​​परीक्षा दें",
    "selectSubjectPrompt": "इसके अध्याय देखने के लिए एक विषय चुनें।",
    "preparingLesson": "आपका पाठ तैयार किया जा रहा है...",
    "oopsError": "ओह! कुछ गलत हो गया।",
    "tryAgain": "पुनः प्रयास करें",
    "quizComplete": "प्रश्नोत्तरी पूरी हुई!",
    "youScored": "आपने {{total}} में से {{score}} अंक प्राप्त किए",
    "aiAnalyzing": "एआई आपके परिणामों का विश्लेषण कर रहा है...",
    "yourNextStep": "आपका अगला कदम",
    "backToChapters": "अध्यायों पर वापस जाएं",
    "continueToNextChapter": "अगले अध्याय पर जाएं",
    "reviewThisChapter": "इस अध्याय की समीक्षा करें",
    "goTo": "इस पर जाएं",
    "loadedFromDB": "डीबी से लोड किया गया",
    "chapterMastery": "अध्याय में निपुणता",
    "keyConcepts": "मुख्य अवधारणाएं",
    "chapterSummary": "अध्याय सारांश",
    "readyToTest": "क्या आप अपने ज्ञान का परीक्षण करने के लिए तैयार हैं?",
    "takeQuizPrompt": "अपनी प्रगति को अद्यतन करने और नई अवधारणाओं में महारत हासिल करने के लिए प्रश्नोत्तरी लें।",
    "generateAdaptiveQuiz": "अनुकूली प्रश्नोत्तरी उत्पन्न करें",
    "aiCreatingQuiz": "एआई आपकी प्रश्नोत्तरी बना रहा है...",
    "chapterMasteredCongrats": "बधाई हो! आपने इस अध्याय में महारत हासिल कर ली है।",
    "mastered": "महारत हासिल",
    "inProgress": "प्रगति में",
    "notStarted": "शुरू नहीं हुआ",
    "markAsUnderstood": "मैंने यह पढ़ लिया है, समझ गया के रूप में चिह्नित करें",
    "stemConnection": "स्टेम कनेक्शन और वास्तविक दुनिया का उदाहरण",
    "visualDiagram": "दृश्य आरेख",
    "aiDrawingDiagram": "एआई आपका आरेख बना रहा है...",
    "diagramFailedError": "एआई एक आरेख बनाने में विफल रहा।",
    "unknownError": "एक अज्ञात त्रुटि हुई।",
    "quizGenerationError": "प्रश्नोत्तरी उत्पन्न करने में विफल।",
    "recommendationError": "सिफारिश उत्पन्न नहीं की जा सकी।",
    "quizResults": "प्रश्नोत्तरी के परिणाम",
    "chapter": "अध्याय",
    "quizScoreSummary": "आपने {{total}} में से {{score}} प्रश्नों के सही उत्तर दिए।",
    "reviewAnswers": "अपने उत्तरों की समीक्षा करें",
    "concept": "अवधारणा",
    "yourAnswer": "आपका उत्तर",
    "notAnswered": "उत्तर नहीं दिया गया",
    "correctAnswerLabel": "सही उत्तर",
    "explanation": "स्पष्टीकरण",
    "backToLesson": "पाठ पर वापस जाएं",
    "adaptiveQuiz": "अनुकूली प्रश्नोत्तरी",
    "question": "प्रश्न",
    "testingConcept": "अवधारणा का परीक्षण",
    "previous": "पिछला",
    "next": "अगला",
    "finishQuiz": "प्रश्नोत्तरी समाप्त करें",
    "preparingDiagnosticTest": "एआई आपकी नैदानिक ​​परीक्षा तैयार कर रहा है...",
    "testGenerationError": "परीक्षा उत्पन्न करने में विफल।",
    "couldNotCreateTest": "परीक्षा नहीं बनाई जा सकी।",
    "backToSubjects": "विषयों पर वापस जाएं",
    "testComplete": "परीक्षा पूरी हुई!",
    "ourRecommendation": "हमारी सिफारिश",
    "diagnosticTestFor": "नैदानिक ​​परीक्षा",
    "diagnosticResultHigh": "आपकी {{subject}} में एक मजबूत नींव है! आप आत्मविश्वास से किसी भी अध्याय के साथ शुरू कर सकते हैं, या शायद \"{{chapter}}\" के साथ खुद को चुनौती दे सकते हैं।",
    "diagnosticResultMid": "आपकी अच्छी शुरुआत है! हम अनुशंसा करते हैं कि आप अपनी समझ को मजबूत करने के लिए पहले अध्याय, \"{{chapter}}\" से शुरू करें।",
    "diagnosticResultLow": "कोई चिंता नहीं, हर विशेषज्ञ कहीं न कहीं से शुरू होता है! आइए एक साथ एक मजबूत नींव बनाएं। शुरू करने के लिए सबसे अच्छी जगह पहला अध्याय है: \"{{chapter}}\" ।",
    "welcomeToPlatform": "अल्फान्यूमरिक में आपका स्वागत है!",
    "selectRolePrompt": "जारी रखने के लिए कृपया अपनी भूमिका का चयन करें।",
    "roleStudent": "छात्र",
    "roleStudentDesc": "अपनी व्यक्तिगत सीखने की यात्रा शुरू करें।",
    "roleTeacher": "शिक्षक",
    "roleTeacherDesc": "प्रगति की निगरानी करें और रिपोर्ट तैयार करें।",
    "roleParent": "अभिभावक",
    "roleParentDesc": "अपने बच्चे की प्रगति और रिपोर्ट देखें।",
    "backToRoleSelection": "भूमिका चयन पर वापस जाएं",
    "teacherDashboard": "शिक्षक डैशबोर्ड",
    "teacherDashboardPrompt": "किसी छात्र के शैक्षणिक प्रदर्शन को देखने और रिपोर्ट तैयार करने के लिए उसका चयन करें।",
    "parentDashboard": "अभिभावक डैशबोर्ड",
    "parentDashboardPrompt": "यहां आपके बच्चे की प्रगति का अवलोकन है। विस्तृत रिपोर्ट देखने के लिए उनकी प्रोफ़ाइल का चयन करें।",
    "backToDashboard": "डैशबोर्ड पर वापस जाएं",
    "aiTools": "एआई उपकरण",
    "generatingReport": "रिपोर्ट तैयार हो रही है...",
    "generateAnalysisReport": "विश्लेषण रिपोर्ट तैयार करें",
    "assigningSheet": "शीट सौंपी जा रही है...",
    "assignPracticeSheet": "अभ्यास शीट सौंपें",
    "aiGeneratedReport": "एआई जनित रिपोर्ट",
    "practiceSheet": "अभ्यास पत्र",
    "askFitto": "फिटो से पूछें",
    "yourQuestion": "आपका प्रश्न",
    "askQuestionPlaceholder": "फिटो के लिए अपना प्रश्न यहाँ लिखें...",
    "cancel": "रद्द करें",
    "submitQuestion": "प्रश्न सबमिट करें",
    "fittoIsThinking": "फिटो सोच रहा है...",
    "fittoResponseTitle": "फिटो का उत्तर",
    "fittoWelcome": "नमस्ते! क्या आपके पास '{{concept}}' के बारे में कोई प्रश्न हैं? मैं मदद के लिए यहाँ हूँ!",
    "performance": "प्रदर्शन",
    "studentQuestions": "छात्र प्रश्न",
    "aiReports": "एआई रिपोर्ट",
    "noPerformanceData": "अभी तक कोई प्रदर्शन डेटा उपलब्ध नहीं है।",
    "noPerformanceDataError": "कमजोर क्षेत्र की पहचान के लिए कोई प्रदर्शन डेटा उपलब्ध नहीं है।",
    "context": "संदर्भ",
    "modelAnswer": "मॉडल उत्तर",
    "pedagogicalNotes": "शैक्षणिक नोट्स (शिक्षक के लिए)",
    "getAIAnswerSuggestion": "एआई शिक्षक नोट्स प्राप्त करें",
    "analyzing": "विश्लेषण हो रहा है",
    "noQuestionsSubmitted": "इस छात्र ने अभी तक कोई प्रश्न प्रस्तुत नहीं किया है।",
    "errorFetchingQuestions": "छात्र प्रश्न प्राप्त करने में त्रुटि।",
    "welcomeBack": "वापस स्वागत है, {{name}}!",
    "dashboardSubtitle": "चलो आज का दिन सीखने के लिए एक महान दिन बनाते हैं।",
    "whatsNext": "आगे क्या?",
    "continueLearningPrompt": "वहीं से शुरू करें जहाँ आपने छोड़ा था या एक नया विषय खोजें।",
    "startLearning": "सीखना शुरू करें",
    "fittoRecommendations": "फिटो की सिफारिशें",
    "practiceThisConcept": "इस अवधारणा का अभ्यास करें",
    "generateExercises": "अभ्यास उत्पन्न करें",
    "generatingExercises": "अभ्यास उत्पन्न हो रहे हैं...",
    "exerciseSummary": "अभ्यास सारांश",
    "yourScore": "आपका स्कोर",
    "correct": "सही!",
    "incorrect": "गलत",
    "close": "बंद करें",
    "quizType": "प्रश्नोत्तरी",
    "exerciseType": "अभ्यास",
    "practiceOn": "अभ्यास: {{context}}",
    "nextQuestion": "अगला प्रश्न",
    "finishPractice": "अभ्यास समाप्त करें",
    "seeExplanation": "स्पष्टीकरण देखें",
    "studentLoginTitle": "छात्र लॉगिन",
    "studentLoginSubtitle": "सीखना शुरू करने के लिए अपना विवरण दर्ज करें।",
    "studentNameLabel": "छात्र का नाम",
    "studentNamePlaceholder": "उदा., अनन्या शर्मा",
    "gradeLabel": "कक्षा",
    "selectGradePlaceholder": "अपनी कक्षा चुनें",
    "loginButton": "लॉगिन करें",
    "logoutButton": "लॉगआउट",
    "loginError": "लॉगिन विफल। कृपया अपना नाम और कक्षा जांचें।",
    "backToRoles": "भूमिकाओं पर वापस",
    "studyPatternsAndTrends": "अध्ययन पैटर्न और रुझान",
    "todaysMission": "आज का मिशन",
    "missionPrompt": "एआई ने आपके लिए एक व्यक्तिगत अगला कदम तैयार किया है।",
    "beginMission": "आज का मिशन शुरू करें",
    "browseCurriculum": "पूरा पाठ्यक्रम ब्राउज़ करें",
    "craftingYourPath": "आपका व्यक्तिगत पथ तैयार किया जा रहा है...",
    "aiReasoning": "यहाँ क्यों है:",
    "missionComplete": "मिशन पूरा हुआ!",
    "greatWork": "बहुत बढ़िया काम! आपने आज के लिए अपना व्यक्तिगत कार्य पूरा कर लिया है।",
    "todaysTask": "आज का कार्य",
    "iqChallenge": "आईक्यू चुनौती",
    "eqChallenge": "भावनात्मक बुद्धिमत्ता परिदृश्य",
    "bestResponse": "सबसे अच्छी प्रतिक्रिया",
    "skill": "कौशल",
    "recentActivity": "हाल की गतिविधि",
    "academicChapter": "{{subject}} में {{chapter}}",
    "iqChallengeCompleted": "आईक्यू चुनौती पूरी हुई",
    "eqChallengeCompleted": "ईक्यू परिदृश्य पूरा हुआ",
    "badgeMastery": "महारत",
    "badgeProficient": "कुशल",
    "badgeImproving": "सुधार",
    "rec_welcome": "आपका स्वागत है! अपनी पहली व्यक्तिगत सिफारिशें प्राप्त करने के लिए अपनी पहली गतिविधि पूरी करें।",
    "rec_strength": "वाह, '{{context}}' ({{score}}%) पर शानदार काम! आप में {{subject}} के लिए एक वास्तविक प्रतिभा है। क्यों न अगले अध्याय के साथ खुद को चुनौती दें?",
    "rec_weakness": "ऐसा लगता है कि {{subject}} में '{{context}}' थोड़ा मुश्किल था ({{score}}%)। कोई बात नहीं! आत्मविश्वास बढ़ाने के लिए अभ्यास करें।",
    "rec_general_tip": "एक जिज्ञासु मन सबसे अच्छा सीखता है! यदि आप कहीं फंस गए हैं तो मुझसे सवाल पूछना न भूलें।",
    "studyPatterns": "अध्ययन पैटर्न",
    "weeklyActivity": "साप्ताहिक गतिविधि",
    "lessActivity": "कम",
    "moreActivity": "अधिक",
    "performanceBySubject": "विषय के अनुसार प्रदर्शन",
    "learningStyle": "सीखने की शैली का विश्लेषण",
    "quizzesTaken": "ली गई प्रश्नोत्तरी",
    "practiceSessions": "अभ्यास सत्र",
    "errorCraftingPathTitle": "आपका पथ बनाने में असमर्थ",
    "errorCraftingPathBody": "हमारे AI से संचार करते समय एक समस्या हुई। कृपया पुनः प्रयास करें।",
    "retryButton": "पुनः प्रयास करें",
    "formulaSheet": "सूत्र पत्र",
    "problemSolvingGuides": "समस्या-समाधान गाइड",
    "practiceProblems": "अभ्यास समस्याएं",
    "conceptual": "वैचारिक",
    "application": "अनुप्रयोग",
    "higherOrderThinking": "उच्च-स्तरीय सोच",
    "viewSolution": "समाधान देखें",
    "commonMistakes": "सामान्य गलतियाँ",
    "competitiveExamCorner": "प्रतियोगी परीक्षा कॉर्नर",
    "experimentsAndSafety": "प्रयोग और सुरक्षा",
    "materialsNeeded": "आवश्यक सामग्री",
    "safetyFirst": "पहले सुरक्षा!",
    "scientificMethodInAction": "वैज्ञानिक विधि क्रिया में",
    "latestDiscoveries": "नवीनतम खोजें और प्रौद्योगिकी",
    "environmentalConnection": "पर्यावरणीय संबंध",
    "interdisciplinaryLinks": "अंतःविषय लिंक",
    "vocabularyDeepDive": "शब्दावली गहन अध्ययन",
    "etymology": "व्युत्पत्ति",
    "timelineOfEvents": "मुख्य घटनाओं की समयरेखा",
    "keyFigures": "मुख्य व्यक्ति और व्यक्तित्व",
    "primarySourceAnalysis": "प्राथमिक स्रोत विश्लेषण",
    "analysis": "विश्लेषण",
    "inDepthCaseStudies": "गहन केस स्टडी",
    "background": "पृष्ठभूमि",
    "conclusion": "निष्कर्ष",
    "grammarSpotlight": "व्याकरण स्पॉटलाइट",
    "literaryDeviceAnalysis": "साहित्यिक उपकरण विश्लेषण",
    "example": "उदाहरण",
    "questionBank": "प्रश्न बैंक",
    "accessQuestionBank": "प्रश्न बैंक एक्सेस करें",
    "questionBankTitle": "एआई प्रश्न बैंक जेनरेटर",
    "questionBankPrompt": "प्रश्नों का एक विविध सेट उत्पन्न करने के लिए एक ग्रेड, विषय और अध्याय का चयन करें।",
    "selectChapterPlaceholder": "एक अध्याय चुनें",
    "generateQuestions": "प्रश्न उत्पन्न करें",
    "generatingQuestions": "एआई प्रश्न उत्पन्न कर रहा है...",
    "noQuestionsGenerated": "कोई प्रश्न उत्पन्न नहीं हुआ। कृपया पुनः प्रयास करें।",
    "questionType": "प्रश्न प्रकार",
    "mcq": "एमसीक्यू",
    "shortAnswer": "संक्षिप्त उत्तर",
    "longAnswer": "दीर्घ उत्तरीय",
    "difficulty": "कठिनाई",
    "easy": "आसान",
    "medium": "मध्यम",
    "hard": "कठिन",
    "bloomsTaxonomy": "ब्लूम की टैक्सोनॉमी",
    "remembering": "याद करना",
    "understanding": "समझना",
    "applying": "लागू करना",
    "analyzing": "विश्लेषण करना",
    "evaluating": "मूल्यांकन करना",
    "creating": "निर्माण करना",
    "markingScheme": "अंकन योजना",
    "tags": "टैग",
    "competencyBased": "योग्यता-आधारित",
    "previousYearQuestion": "पिछले वर्ष का प्रश्न",
    "curriculumGenerator": "पाठ्यक्रम जेनरेटर",
    "curriculumGeneratorPrompt": "किसी विशिष्ट ग्रेड और विषय के लिए पाठ्यक्रम की रूपरेखा तैयार करने के लिए AI का उपयोग करें।",
    "generateOutline": "रूपरेखा तैयार करें",
    "generatingOutline": "AI रूपरेखा तैयार कर रहा है...",
    "noOutlineGenerated": "कोई रूपरेखा तैयार नहीं की गई। कृपया अपने चयन समायोजित करें और पुनः प्रयास करें।",
    "downloadAsSql": "SQL के रूप में डाउनलोड करें",
    "validateCurriculum": "पाठ्यक्रम को मान्य करें",
    "validatingCurriculum": "एआई रूपरेखा को मान्य कर रहा है...",
    "qualityReportTitle": "एआई गुणवत्ता रिपोर्ट",
    "validationError": "एआई से सत्यापन रिपोर्ट प्राप्त करने में विफल।",
    "listenToChapter": "अध्याय सुनें",
    "pauseNarration": "रोकें",
    "resumeNarration": "फिर से शुरू करें",
    "stopNarration": "वर्णन बंद करें",
    "ttsNotSupported": "आपका ब्राउज़र टेक्स्ट-टू-स्पीच का समर्थन नहीं करता है।",
    "viewPrivacyPolicy": "गोपनीयता नीति देखें",
    "privacyPolicyTitle": "हमारी गोपनीयता नीति (छात्रों के लिए!)",
    "backToHome": "होम पर वापस जाएं",
    "privacyIntro": "नमस्ते! अल्फान्यूमरिक में आपकी गोपनीयता हमारे लिए बहुत महत्वपूर्ण है। यह पृष्ठ सरल शब्दों में बताता है कि हम कौन सी जानकारी एकत्र करते हैं और हम आपको सीखने में मदद करने के लिए इसका उपयोग कैसे करते हैं। इसे अपनी सीखने की यात्रा को सुरक्षित और मजेदार रखने के हमारे वादे के रूप में सोचें!",
    "whatInfoWeCollectTitle": "हम कौन सी जानकारी एकत्र करते हैं?",
    "whatInfoWeCollectContent": "जब आप हमारे ऐप का उपयोग करते हैं, तो हम आपके अनुभव को बेहतर बनाने के लिए कुछ चीजों का ध्यान रखते हैं: आपका नाम और ग्रेड, आप कौन से पाठ पढ़ते हैं, आप क्विज़ और अभ्यास अभ्यासों पर कैसे करते हैं, और आप हमारे एआई मेंटर, फिटो से कोई भी प्रश्न पूछते हैं। हम व्यक्तिगत जानकारी एकत्र नहीं करते हैं जो आप हमें नहीं देते हैं, जैसे आपका पता या फोन नंबर।",
    "howWeUseInfoTitle": "हम आपकी जानकारी का उपयोग कैसे करते हैं?",
    "howWeUseInfoContent": "हम आपके सीखने के डेटा का उपयोग केवल आपके लिए एक व्यक्तिगत पथ बनाने के लिए करते हैं! यह हमें यह समझने में मदद करता है कि आप किन विषयों में महान हैं और आपको थोड़ी और मदद की कहाँ आवश्यकता हो सकती है। यह हमारे एआई को आपके लिए एकदम सही अगला पाठ या अभ्यास सुझाने देता है। शिक्षकों और अभिभावकों के लिए, यह जानकारी उन्हें यह देखने में मदद करती है कि आप कैसे कर रहे हैं और आपको बेहतर समर्थन देते हैं।",
    "infoSafetyTitle": "हम आपकी जानकारी को कैसे सुरक्षित रखते हैं",
    "infoSafetyContent": "आपकी जानकारी मजबूत सुरक्षा के साथ सुरक्षित है, जैसे एक गुप्त कोड जिसे केवल हमारा सिस्टम ही समझ सकता है। हम आपकी प्रगति केवल आपके पंजीकृत शिक्षक और माता-पिता के साथ साझा करते हैं। हम आपकी जानकारी कभी किसी को नहीं बेचते हैं।",
    "yourChoicesTitle": "आपके विकल्प",
    "yourChoicesContent": "आप अपनी सीखने की यात्रा के नियंत्रण में हैं। यदि कुछ सही नहीं है तो आप हमेशा अपने माता-पिता या शिक्षक से अपनी जानकारी देखने या अपडेट करने में मदद करने के लिए कह सकते हैं।",
    "changesToPolicyTitle": "इस नीति में परिवर्तन",
    "changesToPolicyContent": "कभी-कभी हम इस नीति को और भी बेहतर बनाने के लिए अपडेट कर सकते हैं। यदि हम कोई बड़ा बदलाव करते हैं, तो हम आपके माता-पिता या शिक्षकों को बताना सुनिश्चित करेंगे।",
    "contactUsTitle": "प्रश्न हैं? किसी वयस्क से मदद मांगें!",
    "contactUsContent": "यदि हमारे गोपनीयता वादे के बारे में आपके कोई प्रश्न हैं, तो कृपया किसी माता-पिता या शिक्षक से हमसे संपर्क करने में मदद करने के लिए कहें। खुश सीखने!",
    "academicQuestion": "शैक्षणिक प्रश्न",
    "missionType_ACADEMIC_REVIEW": "शैक्षणिक समीक्षा",
    "missionType_ACADEMIC_PRACTICE": "शैक्षणिक अभ्यास",
    "missionType_ACADEMIC_NEW": "नया विषय चुनौती",
    "missionType_IQ_EXERCISE": "संज्ञानात्मक कौशल",
    "missionType_EQ_EXERCISE": "भावनात्मक बुद्धिमत्ता",
    "feedbackOnReport": "इस रिपोर्ट पर प्रतिक्रिया?",
    "helpUsImprove": "हमारे AI को बेहतर बनाने में हमारी मदद करें। क्या यह रिपोर्ट उपयोगी थी?",
    "submitFeedback": "प्रतिक्रिया भेजें",
    "feedbackThanks": "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    "commentOptional": "टिप्पणी (वैकल्पिक)",
    "noProblemsAvailable": "इस श्रेणी के लिए कोई समस्या उपलब्ध नहीं है।",
    "learningObjectives": "सीखने के उद्देश्य",
    "keyTheoremsAndProofs": "मुख्य प्रमेय और प्रमाण",
    "formulaDerivations": "सूत्र व्युत्पत्ति",
    "solvedNumericalProblems": "हल किए गए संख्यात्मक प्रश्न",
    "keyLawsAndPrinciples": "मुख्य नियम और सिद्धांत",
    "conceptMap": "अध्याय अवधारणा मानचित्र",
    "learningTricksAndMnemonics": "सीखने की तरकीबें और स्मरक",
    // FIX: Add missing comma to prevent syntax error
    "higherOrderThinkingQuestions": "उच्च-स्तरीय सोच कॉर्नर",
};

const hiCurriculumTranslations: Record<string, string> = {
  "Grade 1": "कक्षा 1",
  "Starting the journey of learning.": "सीखने की यात्रा की शुरुआत।",
  "English": "अंग्रेज़ी",
  "The Alphabet & Phonics": "वर्णमाला और ध्वन्यात्मकता",
  "Vowels and Consonants": "स्वर और व्यंजन",
  "Simple Words & Sentences": "सरल शब्द और वाक्य",
  "Rhyming Words": "तुकबंदी वाले शब्द",
  "Story Time: Listening and Reciting": "कहानी का समय: सुनना और सुनाना",
  "Hindi": "हिन्दी",
  "Varnmala (Alphabet)": "वर्णमाला",
  "Swar and Vyanjan": "स्वर और व्यंजन",
  "Do Akshar Wale Shabd (Two-letter words)": "दो अक्षर वाले शब्द",
  "Choti Kavitaayein (Short Poems)": "छोटी कविताएँ",
  "Mathematics": "गणित",
  "Numbers up to 20": "20 तक की संख्याएँ",
  "Shapes and Space": "आकृतियाँ और स्थान",
  "Simple Addition & Subtraction": "सरल जोड़ और घटाव",
  "Measurement (Length and Weight)": "माप (लंबाई और वजन)",
  "Time": "समय",
  "EVS": "ईवीएस",
  "My Family and Me": "मेरा परिवार और मैं",
  "Our Body Parts": "हमारे शरीर के अंग",
  "Plants Around Us": "हमारे आस-पास के पौधे",
  "Animals Around Us": "हमारे आस-पास के जानवर",
  "Our Helpers": "हमारे सहायक",
  "Festivals": "त्योहार",
  "Computer Science": "कंप्यूटर विज्ञान",
  "Getting to Know Computers": "कंप्यूटर से परिचय",
  "Using the Mouse and Keyboard": "माउस और कीबोर्ड का उपयोग",
  "Fun with Digital Paint": "डिजिटल पेंट के साथ मज़ा",
  "Physical Education": "शारीरिक शिक्षा",
  "Fun Body Movements": "मजेदार शारीरिक गतिविधियां",
  "Playing Together (Simple Games)": "एक साथ खेलना (सरल खेल)",
  "Basic Yoga Poses": "बुनियादी योग आसन",
};

const translations: Record<string, Record<string, string>> = {
  en: enTranslations,
  hi: hiTranslations,
};

const curriculumTranslations: Record<string, Record<string, string>> = {
  hi: hiCurriculumTranslations,
  en: {} // English curriculum keys are the same as the source, so no mapping needed.
};

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  tCurriculum: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('alfanumrik-language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('alfanumrik-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
  };

  const t = (key: string, replacements?: { [key: string]: string | number }) => {
    let translation = translations[language]?.[key] || translations['en']?.[key] || key;
    if (replacements) {
      Object.keys(replacements).forEach(rKey => {
        translation = translation.replace(`{{${rKey}}}`, String(replacements[rKey]));
      });
    }
    return translation;
  };

  const tCurriculum = (key: string) => {
    return curriculumTranslations[language]?.[key] || key;
  };


  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCurriculum }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
