name: Adaptive Learning Daily Sync

on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2 AM UTC

jobs:
  adaptive_sync:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Supabase Login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --access-token $SUPABASE_ACCESS_TOKEN

      - name: Link Supabase Project
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: Run adaptive_mastery_compute function
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/adaptive_mastery_compute"

      - name: Run adaptive_content_assign function
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/functions/v1/adaptive_content_assign"
